name: "Teams Manager"
description: "Manage teams repository and members"
inputs:
  app_id:
    description: "github app id"
    required: true
  installationId:
    description: "github app installationId"
    required: true
  private_key:
    description: "github app private key"
    required: true
  config_file:
    description: "manager config file"
    required: true
  generate_yaml:
    description: "generate Yaml for org"
    required: false
    default: false
  update_teams:
    description: "update teams settings by local yaml for org"
    required: false
    default: true

runs:
  using: "node16"
  main: "dist/index.js"
